spring:
  datasource:
    url: jdbc:h2:mem:testdb
    name:
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true

flowable:
  mailServerHost: smtp.gmail.com
  mailServerPort: 587
  mailServerUserName: rh-cynapsys@cynapsys.de
  mailServerPassword: tunisie2014!
  mailServerUseTls: true
